require("configs.autopairs")
require("configs.bufferline")
require("configs.catppuccin")
require("configs.cmp")
require("configs.alpha")
require("configs.gitsigns")
require("configs.lualine")
require("configs.nvim_tree")
require("configs.telescope")
require("configs.toggleterm")
require("configs.treesitter")

